{{- if ne .Values.cloudflare.tunnelToken "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared.envName" . }}
  labels:
    {{ include "cloudflared.labels" . | nindent 4 }}
data:
  TUNNEL_TOKEN: {{ .Values.cloudflare.tunnelToken | b64enc }}
{{- else }}
{{- if eq .Values.cloudflare.secretName "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared.secretName" . }}
  labels:
    {{ include "cloudflared.labels" . | nindent 4 }}
stringData:
  credentials.json: |-
    {
      "AccountTag": {{ .Values.cloudflare.account | quote  }},
      "TunnelID": {{ .Values.cloudflare.tunnelId | quote }},
      "TunnelSecret": {{ .Values.cloudflare.secret | quote }}
    }
{{- end }}
{{- end }}
