name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  release:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Helm
        run: |
          sudo apt-get update --yes
          sudo apt-get install curl gpg apt-transport-https --yes
          curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm

      - name: Package and Push
        shell: bash
        run: |
          set -e
          for chart in $(ls charts); do
            if [ -d "./charts/$chart" ]; then
              if ! git diff --quiet HEAD^ -- "./charts/$chart" ; then
                pushd "./charts/$chart"
                echo "Packaging chart: $chart"
                helm package .

                echo "Pushing chart: $chart"
                version=$(yq '.version' ./Chart.yaml)
                helm push "$chart-$version.tgz" "oci://ghcr.io/dacbd/helm-charts"
                popd
                echo "---------------------------------"
              else
                echo "No changes detected in chart \"$chart\"; skipping Package and Push."
              fi
            fi
          done
